# Generated by Django 3.2.12 on 2022-04-22 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('profile_image', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_deleted', models.BooleanField(default=False)),
                ('posts', models.ManyToManyField(related_name='post_user', to='uploads.Posts')),
            ],
        ),
    ]
