# Generated by Django 3.2.12 on 2022-04-22 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
